CONTINUOUS = "CONTINUOUS"
BINARY = "BINARY"
INTEGER = "INTEGER"

STATUS_OPTIMAL_SOL = "optimal"
STATUS_INFEASIBLE = "infeasible"
STATUS_GAPLIMIT = "gaplimit"
STATUS_USERINTERRUPT = "userinterrupt"
STATUS_TIMELIMIT = "timelimit"
