CONTINUOUS = "CONTINUOUS"
BINARY = "BINARY"
INTEGER = "INTEGER"
ZERO = 0.0
BIN_0, INT_0 = 0, 0
BIN_1, INT_1 = 1, 1

STATUS_OPTIMAL_SOL = "optimal"
STATUS_INFEASIBLE = "infeasible"
STATUS_GAPLIMIT = "gaplimit"
STATUS_USERINTERRUPT = "userinterrupt"
STATUS_TIMELIMIT = "timelimit"
